version: '3.8'

services:
  app:
    image: 'discovery:latest'
    build:
      context: .
    container_name: discoveryContainer
    ports:
      - "8050"
    networks:
      - spring

networks:
  postgres:
    driver: bridge
  spring:
    driver: bridge