eureka:
  instance:
    hostname: localhost
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka/

server:
  port: 8050
spring:
  application:
    name: tracktimes
  config:
    import: optional:configserver:http://localhost:8888
  datasource:
    driver-class-name: org.postgresql.Driver
    url: jdbc:postgresql://localhost:5433/abdallahehab
    username:
    password:
  jpa:
    hibernate:
      ddl-auto: create
    database: postgresql
    database-platform: org.hibernate.dialect.PostgreSQLDialect
  cache:
    type: redis
  data:
    redis:
      host: localhost
      port: 6379
  jackson:
    serialization:
      write-dates-as-timestamps: false
#  devtools:
#    restart:
#      enabled: true
#      exclude: static/**,public/**
#    restart:
#      enabled: true
#      exclude: /com/hubstaffmicroservices/tracktime/UpdatedClass\.java




