eureka:
  instance:
    hostname: localhost
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka/

server:
  port: 8050
spring:
  application:
    name: tracktimes
  config:
    import: optional:configserver:http://localhost:8050
  datasource:
    driver-class-name: org.postgresql.Driver
    url: jdbc:postgresql://localhost:5432/abdallahehab
    username: postgres
    password: postgres
  jpa:
    hibernate:
      ddl-auto: create
    database: postgresql
    database-platform: org.hibernate.dialect.PostgreSQLDialect
    rabbitmq:
      addresses: localhost:5672
#  cache:
#    type: redis
#  data:
#    redis:
#      host: localhost
#      port: 6379


